### ISSUE TITLE
Unexpected behaviour for ThreadLocals

### ISSUE THREAD

**Issue by FSchliephacke** [jsampson/guarded-executor#6]
Hi Justin,

the API looks very convenient, but the design decision to let any thread execute a waiting Runnable leads to inconsistencies with other locking mechanisms when using ThreadLocals:

```
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class TestGuardedExecutorThreadLocal
{
	private ThreadLocal<Integer> threadLocal;

	@BeforeEach
	void initThreadLocal()
	{
		threadLocal = new ThreadLocal<>();
	}

	@Test
	void threadLocalGuardedExecutor()
	{
		final GuardedExecutor guardedExecutor = new GuardedExecutor();
		executeTest(() ->
		{
			guardedExecutor.execute(() ->
			{
				threadLocal.set(threadLocal.get() + 1);
			});
		});
	}

	@Test
	void threadLocalLock()
	{
		final Lock lock = new ReentrantLock();
		executeTest(() ->
		{
			lock.lock();
			try
			{
				threadLocal.set(threadLocal.get() + 1);
			} finally
			{
				lock.unlock();
			}
		});
	}

	private void executeTest(final Runnable synchronizedIncrement)
	{
		final int threadCount = 1000;
		final List<AssertionError> errors = Collections.synchronizedList(new ArrayList<>(threadCount));
		final CountDownLatch start = new CountDownLatch(threadCount);
		final CountDownLatch finish = new CountDownLatch(threadCount + 1);
		for (int i = 0; i < threadCount; i++)
		{
			new Thread(() ->
			{
				final int random = ThreadLocalRandom.current().nextInt();
				threadLocal.set(random);
				start.countDown();

				synchronizedIncrement.run();

				try
				{
					assertEquals(random + 1, threadLocal.get());
				} catch (final AssertionError error)
				{
					errors.add(error);
				}
				finish.countDown();
			}).start();
		}
		finish.countDown();
		for (final AssertionError error : errors)
		{
			throw error;
		}
	}
}
```

**Comment by FSchliephacke** [comment]
Sorry, I didn't read the documentation careful enough. You clearly mention it in the API documentation.

**Comment by jsampson** [comment]
Hi @FSchliephacke, thanks for your interest in GuardedExecutor! You're right to observe that this is potentially unexpected behavior. I do hope that the documentation is helpful, but of course documentation alone doesn't compensate for a surprising design. This is one big reason why I decided to call it an Executor instead of a Lock, because programmers should expect an Executor to potentially run tasks in different threads.

May I ask, how did you come across GuardedExecutor? This is a long-running side project that I do hope to incorporate into an open source library at some point, but I haven't had time to push it forward lately.

**Comment by FSchliephacke** [comment]
Maybe you should mention it right away in the wiki. After reading the introduction and motivation I was keen to dive into the design overview, but as soon as I read that you are switching threads I was confused regarding the use of ThreadLocals. Just a short, prominent note about that at the beginning of the readme would be helpful.

In the introduction it says
"I'm the original author of Guava's Monitor class, and I have created a replacement for it called GuardedExecutor."
That sentence is a bit misleading.

Regarding your question: Some time ago I wrote a wrapper around ReentrantLock, similar to, but of course not as fully featured as your Guava Monitor implementation. I replaced my implementation with Monitor and was still a bit annoyed by the need to explicitly call Monitor::enter and Monitor::leave, so I started digging a bit and stumbled across GuardedExecutor. As I was fairly impressed by Monitor, I wanted to look into this, too.

The whole "encapsulate the guarded code in lambdas" idea is really great, but the project I am currently working on is neither performance critical, nor am I allowed to use code from outside the company's repository, so I will probably just write a thin wrapper around Monitor :-)
